get most view videos controller
OngDev/yt-api pull request #25
Opened 2020-09-16 10:41 UTC by dattp

* get most view videos controller

2020-09-28 03:48 UTC, MiloNguyen95 commented
@dattp Em check mấy cái error github nó comment trước đã nha.

2020-10-05 15:22 UTC, MiloNguyen95 requested changes
Tổng thể ok, anh có 1 comment nhỏ thôi.
Với lại em có đinh thêm test cho router vs controller như nãy mình discuss không?

2020-10-05 15:22 UTC, MiloNguyen95 commented on src/routes/video.routes.js
> +router.get('/getMostViewVideos/:videoNumber', (req, res) => VideoController.getMostViewVideos(req, res));
anh nghĩ chỗ này nên dùng là /getMostViewVideos?videoNumber=...

2020-10-06 01:22 UTC, dattp commented
> Tổng thể ok, anh có 1 comment nhỏ thôi.
> Với lại em có đinh thêm test cho router vs controller như nãy mình discuss không?

em có anh. Nhưng em nghĩ sẽ viết test cho controller thôi. Chứ router em nghĩ ko cần thiết lắm, mà em cũng chưa biết sẽ viết test cho router như nào ạ.

2020-10-06 08:48 UTC, MiloNguyen95 commented
> > Tổng thể ok, anh có 1 comment nhỏ thôi.
> > Với lại em có đinh thêm test cho router vs controller như nãy mình discuss không?
> 
> em có anh. Nhưng em nghĩ sẽ viết test cho controller thôi. Chứ router em nghĩ ko cần thiết lắm, mà em cũng chưa biết sẽ viết test cho router như nào ạ.

Oke

2020-10-07 04:26 UTC, dattp commented
> Oke

anh @MiloNguyen95  review lại cho em nha. Em vừa đẩy thêm phần unit test và 1 vài file nó đang bị format lại thôi ạ.

2020-10-09 13:03 UTC, MiloNguyen95 approved these changes
Cái em test đang là integration test nha, chứ ko phải unit test.
Nhưng mà sau này có service thêm vào cũng ok

2020-10-09 13:03 UTC, merged