get video in playlist controller
OngDev/yt-api pull request #28
Opened 2020-10-20 14:23 UTC by dattp

* get video in playlist - controller

2020-10-30 14:52 UTC, OngDevTech requested changes

2020-10-30 14:52 UTC, OngDevTech commented on src/routes/video.routes.js
router.get('/videos/:id', (req, res) => VideoController.videoById(req, res));
router.get('/videos/topthree', (req, res) => VideoController.getMostViewVideos(req, res));
router.get('/videos(?playlistId)', (req, res) => VideoController.getVideosByPlayListId(req, res));

2020-11-08 06:35 UTC, OngDevTech commented on src/routes/video.routes.js
> +router.get('/videos/playlist', (req, res) => VideoController.getVideosByPlayListId(req, res));
Cái này có thể là kiểu videos?playlistId= được luôn ko e

2020-11-08 06:35 UTC, OngDevTech approved these changes
Xí nữa thôi :v

2020-11-08 06:38 UTC, OngDevTech requested changes
Em check chỗ cái videos/playlist nha, mình có thể dùng kiểu videos?playlistid=...

2020-11-08 12:12 UTC, dattp commented on src/routes/video.routes.js
> +router.get('/videos/playlist', (req, res) => VideoController.getVideosByPlayListId(req, res));
oki anh :D

2020-11-13 04:49 UTC, MiloNguyen95 approved these changes

2020-11-13 04:50 UTC, merged