Get videos
OngDev/yt-api pull request #30
Opened 2020-11-16 14:44 UTC by dattp

* Get videos with pagination
* Add DTO.

2020-11-16 14:48 UTC, dattp commented
Anh @MiloNguyen95  review hộ em pull request.
Em có bổ sung luôn phần DTO ở trong đây để convert dữ liệu lấy từ DB sang object chung để response về.
Anh check hộ em luôn phần convention của naming route nhe. Em có sửa lại 1 chút.

2020-11-20 07:51 UTC, MiloNguyen95 commented on src/controllers/video.controller.js
> +    const videosDTO = VideoDTO.dtoListVideo(videos);
Tên cái function dtoListVideo nên là toVideoDtoList nghe, function là động từ

2020-11-20 07:53 UTC, MiloNguyen95 commented on src/dtos/video.dto.js
> +import VideoConst from '../constants/video.constant';
file này nên là mapper nha e, kiểu VideoMapper

2020-11-20 07:54 UTC, MiloNguyen95 commented on src/routes/video.routes.js
> +router.get('/videos/playlist/:id', (req, res) => VideoController.getVideosByPlayListId(req, res));
route cái này nên là videos?playlistId=... nằm trong params chứ ko phải query

2020-11-20 07:55 UTC, MiloNguyen95 requested changes
A có 1 vài comment nha

2020-11-20 08:54 UTC, dattp commented on src/routes/video.routes.js
> +router.get('/videos/playlist/:id', (req, res) => VideoController.getVideosByPlayListId(req, res));
em hơi phân vân chỗ này. Nếu để là `videos?playlistId=` thì route sẽ khai báo là `/videos` thì nó sẽ bị trùng với cái route cho function get videos theo pagination anh ạ.
Không thì em khai báo kiểu `/videos/playlist? playlistId=` đc không anh.

2020-11-24 10:09 UTC, MiloNguyen95 commented
Đạt ơi, anh có mấy cái comment đó, em check thử nha @dattp

2020-11-27 14:41 UTC, MiloNguyen95 commented on src/routes/video.routes.js
> +router.get('/videos/playlist/:id', (req, res) => VideoController.getVideosByPlayListId(req, res));
À cái này em có thể gộp vào, xong trong (req, res) => ... trong này em check cái query.playlistId, null thì get all, ko thì get by playlist id

2020-12-01 14:33 UTC, dattp commented
> Đạt ơi, anh có mấy cái comment đó, em check thử nha @dattp

Em đã sửa lại theo comment của anh. Anh review lại giúp em nha.

2020-12-07 08:50 UTC, MiloNguyen95 commented on src/controllers/video.controller.js
> +  let { skip, limit, playlistid } = req.query;
Em check cái này nè, tách th playlistId ra nha, với lại, đặt playlistId chứ đừng là playlistid nha

2020-12-07 08:51 UTC, MiloNguyen95 requested changes
Comment nhỏ

2020-12-09 13:25 UTC, MiloNguyen95 approved these changes

2020-12-09 13:25 UTC, merged